CricketPlayers/Models/ErrorViewModel.cs
using System;

namespace CricketPlayers.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CricketPlayers/Models/Player.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CricketPlayers.Models
{
    public class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string PlayingRole { get; set; }

        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }
        public string BattingStyle { get; set; }
        public string BowlingStyle { get; set; }
        public int CricInfoId { get; set; }
    }

    public enum PlayingRole
    {
        TopOrderBatsman,
        MiddleOrderBatsman,
        Finisher,
        Batsman,
        Bowler,
        DeathBowler,
        AllRounder,
        Wicketkeeper,
        WicketkeeperTopOrderBatsman,
        WicketkeeperMiddleOrderBatsman,
        WicketkeeperFinisher
    }
}

CricketPlayers/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CricketPlayers.Models;

namespace CricketPlayers.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CricketPlayers/Controllers/PlayersController.cs
using System.Linq;
using System.Threading.Tasks;
using CricketPlayers.Data;
using CricketPlayers.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CricketPlayers.Controllers
{
    public class PlayersController : Controller
    {
        private readonly CricketPlayersContext _context;

        public PlayersController(CricketPlayersContext context)
        {
            _context = context;
        }

        // GET: Players
        public async Task<IActionResult> Index()
        {
            return View(await _context.Players.OrderBy(player => player.Name).Take(100).ToListAsync());
        }

        // GET: Players/Search/rohit
        public async Task<IActionResult> Search(string playerName)
        {
            var listAsync = await _context.Players.Where(player => player.FullName.Contains(playerName)).ToListAsync();
            return View(listAsync);
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,FullName,PlayingRole,FieldingPosition,DateOfBirth,BattingStyle,BowlingStyle,CricInfoId, IsActive, CricsheetName, Identifier")] Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,FullName,PlayingRole,FieldingPosition,DateOfBirth,BattingStyle,BowlingStyle,CricInfoId,IsActive, CricsheetName, Identifier")] Player player)
        {
            if (id != player.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Players.FindAsync(id);
            _context.Players.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
            return _context.Players.Any(e => e.Id == id);
        }
    }
}

CricketPlayers/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CricketPlayers/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CricketPlayers/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

CricketPlayers/Views/Players/Create.cshtml
@model CricketPlayers.Data.Entities.Player

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayingRole" class="control-label"></label>
                <input asp-for="PlayingRole" class="form-control" />
                <span asp-validation-for="PlayingRole" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BattingStyle" class="control-label"></label>
                <input asp-for="BattingStyle" class="form-control" />
                <span asp-validation-for="BattingStyle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BowlingStyle" class="control-label"></label>
                <input asp-for="BowlingStyle" class="form-control" />
                <span asp-validation-for="BowlingStyle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CricInfoId" class="control-label"></label>
                <input asp-for="CricInfoId" class="form-control" />
                <span asp-validation-for="CricInfoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <input asp-for="IsActive" class="form-control" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CricsheetName" class="control-label"></label>
                <input asp-for="CricsheetName" class="form-control" />
                <span asp-validation-for="CricsheetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Identifier" class="control-label"></label>
                <input asp-for="Identifier" class="form-control" />
                <span asp-validation-for="Identifier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CricketPlayers/Views/Players/Delete.cshtml
@model CricketPlayers.Data.Entities.Player

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlayingRole)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlayingRole)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BattingStyle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BattingStyle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BowlingStyle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BowlingStyle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CricInfoId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CricInfoId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CricsheetName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CricsheetName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Identifier)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Identifier)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CricketPlayers/Views/Players/Details.cshtml
@model CricketPlayers.Data.Entities.Player

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlayingRole)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlayingRole)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BattingStyle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BattingStyle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BowlingStyle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BowlingStyle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CricInfoId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CricInfoId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CricsheetName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CricsheetName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Identifier)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Identifier)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CricketPlayers/Views/Players/Edit.cshtml
@model CricketPlayers.Data.Entities.Player

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayingRole" class="control-label"></label>
                <input asp-for="PlayingRole" class="form-control" />
                <span asp-validation-for="PlayingRole" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BattingStyle" class="control-label"></label>
                <input asp-for="BattingStyle" class="form-control" />
                <span asp-validation-for="BattingStyle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BowlingStyle" class="control-label"></label>
                <input asp-for="BowlingStyle" class="form-control" />
                <span asp-validation-for="BowlingStyle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CricInfoId" class="control-label"></label>
                <input asp-for="CricInfoId" class="form-control" />
                <span asp-validation-for="CricInfoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <input asp-for="IsActive" class="form-control" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CricsheetName" class="control-label"></label>
                <input asp-for="CricsheetName" class="form-control" />
                <span asp-validation-for="CricsheetName" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Identifier" class="control-label"></label>
                <input asp-for="Identifier" class="form-control" />
                <span asp-validation-for="Identifier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CricketPlayers/Views/Players/Index.cshtml
@model IEnumerable<CricketPlayers.Data.Entities.Player>

@{
    ViewData["Title"] = "Index";
}

<h2>All Players</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Search">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input class="form-control" name="playerName"/>
            </div>

            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-default" />         
                </div>
        </form>
    </div>
</div>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayingRole)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BattingStyle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BowlingStyle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CricInfoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CricsheetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Identifier)
            </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
         @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlayingRole)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BattingStyle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BowlingStyle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CricInfoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CricsheetName)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.Identifier)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
         }
    </tbody>
</table>

<p>
    <a asp-action="Create">Create New</a>
</p>

CricketPlayers/Views/Players/Search.cshtml
@model IEnumerable<CricketPlayers.Data.Entities.Player>

@{
    ViewData["Title"] = "Search";
}

<h2>Players</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Search">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input class="form-control" name="playerName"/>
            </div>

            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-default" />         
            </div>
        </form>
    </div>
</div>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayingRole)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BattingStyle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BowlingStyle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CricInfoId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CricsheetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Identifier)
            </th>
            <th> Action </th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlayingRole)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BattingStyle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BowlingStyle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CricInfoId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CricsheetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Identifier)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<p> <a asp-action="Index">Back to List</a> </p>

CricketPlayers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CricketPlayers</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Players" asp-action="Index" class="navbar-brand">CricketPlayers</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CricketPlayers</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>